apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
        - name: backendapi
          image: node:16
          ports:
            - containerPort: 3000
          command: ['npm', 'run', 'dev']
