apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendapi
  template:
    metadata:
      labels:
        app: backendapi
    spec:
      containers:
        - name: backendapi
          image: timothyjblew/bus-backend # pull from docker hub
          ports:
            - containerPort: 3000
          command: ['npm', 'run', 'dev']
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi 
      
