apiVersion: v1
kind: Service
metadata:
  name: backendapi
spec:
  selector:
    app: backendapi
  ports:
    - protocol: TCP
      port: 80 # listens on port 80 externally
      targetPort: 3000 # forward to internal pods
  type: LoadBalancer
